[project]
name = "rcm-stage1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastmcp>=2.9.2",
    "google-adk>=1.5.0",
    "httpx>=0.28.1",
    "sqlglot>=26.31.0",
]
